# ===============================
# = PROD
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic_dbspring?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: A$dmin123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
